title: NeneXclusives
email: info@nenexclusive.com
description: Online Store for Eletronics Stuff
url: "nenexclusives.com"
author: Ivo Zinenda

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-email-protect
  - jekyll-autolink_email
  - algoliasearch-jekyll

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - bower_components

defaults:
- scope:
    path: ""
    type: products
  values:
    title: ""
    image: ""
    price: 0.00
    sku: ""
    weight: 0
    layout: page

- scope:
    path: ""
    type: pages
  values:
    title: ""
    description:
    images: ""
    layout: default

collections:
  computatadores:
  smartfones:
  impressoras:
  bolsas:
  joias:
  relogios:

image: /assets/img/favicons/logotype.svg
logo: /assets/img/favicons/logo.svg

color: "#ff0844"

sass:
  sass_dir: /assets/_sass
  style: compressed

# algolia
algolia:
  application_id: 'JBQ08JBNOR'
  index_name:     'NeneXclusive'
  read_only_api_key: a5236f8df79552c1b6825b9359ab6e4c
  excluded_files:
    - 404.html
    - index.html