---
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: price
  label: Price
  type: text
  hidden: false
  default: 0
- type: file
  name: image
  label: Image
- name: sku
  label: Sku
  type: text
  hidden: false
  default: ''
- name: weight
  label: Weight
  type: text
  hidden: false
  default: 0
- name: layout
  label: Layout
  type: text
  hidden: false
  default: page
