---
pages:
- _perifericos/jy-17-bluetooth-speaker.md
- _perifericos/sony-headphone.md
- _perifericos/studio-bluetooth-yx-818.md
- _perifericos/hp-wireless-mouse.md
- _perifericos/jbl-029-headphones.md
- _perifericos/kts-386-wireless-speaker.md
- _impressoras/hp-laserjet-toner-83a.md
- _impressoras/hp-laserjet-toner-78a.md
- _impressoras/hp-laserjet-toner-36a.md
- _impressoras/hp-laserjet-toner-35a.md
- _impressoras/hp-laserjet-toner-85a.md
- _impressoras/kyocera-km-1815-toner-cartridge.md
- _impressoras/tinteiro-xerox.md
- _impressoras/tinteiro-samsung-k504.md
- _impressoras/tinteiro-samsung-xpress-111s.md
- _impressoras/tinteiro-samsung-xpress-101s-black.md
- _impressoras/tinteiro-lexmark.md
- _smartfones/samsung-galaxy-pocket-2.md
- _smartfones/apple-iphone-6.md
- _smartfones/samsung-galaxy-s6-edge.md
- _computatadores/macbook-air-core-i5.md
hide_body: true
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: price
  label: Price
  type: text
  hidden: false
  default: 0
- type: file
  name: image
  label: Image
- name: sku
  label: Sku
  type: text
  hidden: false
  default: ''
- name: weight
  label: Quantity
  type: text
  hidden: false
  default: 0
- name: layout
  label: Layout
  type: text
  hidden: false
  default: page
